### ISSUE TITLE
Continue on NXDOMAIN in dns lookups

### ISSUE THREAD

**Issue by mschneider82** [albertito/spf#5] opened 2022-07-04 10:14 UTC
In case that an MX record has more than one host listed, and some of these hosts are not resolvable (RCODE3 NXDOMAIN), the spf library returned an error

https://datatracker.ietf.org/doc/html/rfc7208#section-5 
`   Several mechanisms rely on information fetched from the DNS.  For
   these DNS queries, except where noted, if the DNS server returns an
   error (RCODE other than 0 or 3) or the query times out, the mechanism
   stops and the topmost check_host() returns "temperror".  If the
   server returns "Name Error" (RCODE 3), then evaluation of the
   mechanism continues as if the server returned no error (RCODE 0) and
   zero answer records.`

I would expect that it continues and skips the temperrors

**Comment by albertito** [comment] 2022-07-04 22:25
Thanks a lot for reporting this problem, and also for sending a patch for it!

Let's discuss the fix itself in the pull request.

**Comment by albertito** [comment] 2022-07-08 12:32
This is now fixed in commit 5cf5998b019 which is included in the `next` branch.

I'll leave it there for a couple of weeks, and give it some exposure. Eventually I will move it to `master`, as usual. I'll leave this open until then.

Thank you!

**Comment by mschneider82** [comment] 2022-07-15 12:04
unfortunately there are domains with invalid `include:` domains, it should be skipped
I have also checked if this happens in `exists:` and `redirect=` as well, `redirect=` is also fixed by the PR, `exists:` was working properly.

**Comment by mschneider82** [comment] 2022-07-25 08:02
@albertito i had this issue on 2 different domains on incoming emails. so its actually a bug, hope you will find the time to review and merge

**Comment by albertito** [comment] 2022-07-29 14:55
Thanks for letting me know about this happening 2 times on the wild, it definitely raises the urgency.

Sorry for the delay, I was basically offline for nearly 2 weeks. I plan to review and merge this on Sunday once my connectivity stabilizes :)

**Comment by albertito** [comment] 2022-08-01 21:00
Now that I'm back, I've been looking at this more carefully and adding some more test cases to validate behaviour on NXDOMAIN answers.

While doing that, I caught a few things to improve:
- The yaml tests don't automatically return NXDOMAIN errors, but just empty values and a nil error by default. That can cause tests to accidentally pass when they should fail. Although none of the current tests seem affected, it caught me when writing new ones. This is fixed in commit 4cb0f61d754493b299493f6a574cb26688bdbb5f.
- The top-level Check is treating all permanent errors as nxdomain, but we should distinguish between the two. This is fixed in commit a4245fd79e565067ead00ed5338012b9cf835441. 

Now, for the specific handling of NXDOMAIN under different circumstances:

- For `mx`, I think there was a bug and the fix we previously discussed (and merged in `next`, now commit 32d5fc8b2ac8ff85ac34a190e45dc2a7b5b5967a) is valid and reasonable.
- For `include`, I think the current behaviour is correct. An `include:doesnotexist` term should return None, not Fail, because that's what the SPF check returns if there is no SPF record. Then it gets handled as per the [RFC table](https://datatracker.ietf.org/doc/html/rfc7208#section-5.2). There's a [test covering this already](https://github.com/albertito/spf/blob/a691aa8177e1c2d82606912e722808d18fad1d8b/spf_test.go#L73).
- For `redirect`, I also think the current behaviour is correct: the recursive Check call should return None if the record does not exist, and in that case, it gets turned into PermError correctly [as per rfc](https://datatracker.ietf.org/doc/html/rfc7208#section-6.1).
- For `exists`, there's an explicit check and if there's any DNS permanent error (including NXDOMAIN) we assume a non-match, so I also think the current behaviour is correct.

I've added test cases for the scenarios the library already handled well (commit 54e4d8f10a44e2d3dd03de042456bd96f4445b5e), and adjusted your patch to also extend those tests and cover the MX resolution (commit 32d5fc8b2ac8ff85ac34a190e45dc2a7b5b5967a).

So, all in all, I think that set of changes should fix all the known problems with nxdomain answers (including your fix for MX behaviour), and extend test coverage to prevent any regressions on it; and we should be able to close this issue.

What do you think?

In the meantime, I'm going to run this on my smtp server for a few days just in case.

Thanks again!

**Comment by albertito** [comment] 2022-08-08 17:06
I've pushed all the fixes for these set of issues (commit 32d5fc8b2ac8ff85ac34a190e45dc2a7b5b5967a and c4a8b797d0fd6d88880a41d0ad855dc933dc0ac3 are the most relevant) to branch `master` and made a new release including them.

So I'm going to close this now, but please reopen and/or comment further if you think there are still issues!

Thanks a lot!

**Closed** 2022-08-08 17:07 UTC
Labels: bug
